# Generated by Django 5.0.6 on 2024-06-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='position',
            field=models.CharField(blank=True, default='company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='distributor_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='self_distributor',
            field=models.CharField(blank=True, default='self', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Company_Payment_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('days', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Register_Login.companydetails')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Register_Login.distributordetails')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTermsUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_action', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.distributordetails')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.paymentterms')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousPaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_plans', to='Register_Login.companydetails')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_plans', to='Register_Login.distributordetails')),
            ],
        ),
        migrations.CreateModel(
            name='TrialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('interested_in_buying', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='ZohoModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(default=0, null=True)),
                ('price_list', models.IntegerField(default=0, null=True)),
                ('stock_adjustment', models.IntegerField(default=0, null=True)),
                ('godown', models.IntegerField(default=0, null=True)),
                ('cash_in_hand', models.IntegerField(default=0, null=True)),
                ('offline_banking', models.IntegerField(default=0, null=True)),
                ('upi', models.IntegerField(default=0, null=True)),
                ('bank_holders', models.IntegerField(default=0, null=True)),
                ('cheque', models.IntegerField(default=0, null=True)),
                ('loan_account', models.IntegerField(default=0, null=True)),
                ('customers', models.IntegerField(default=0, null=True)),
                ('invoice', models.IntegerField(default=0, null=True)),
                ('estimate', models.IntegerField(default=0, null=True)),
                ('sales_order', models.IntegerField(default=0, null=True)),
                ('recurring_invoice', models.IntegerField(default=0, null=True)),
                ('retainer_invoice', models.IntegerField(default=0, null=True)),
                ('credit_note', models.IntegerField(default=0, null=True)),
                ('payment_received', models.IntegerField(default=0, null=True)),
                ('delivery_challan', models.IntegerField(default=0, null=True)),
                ('vendors', models.IntegerField(default=0, null=True)),
                ('bills', models.IntegerField(default=0, null=True)),
                ('recurring_bills', models.IntegerField(default=0, null=True)),
                ('vendor_credit', models.IntegerField(default=0, null=True)),
                ('purchase_order', models.IntegerField(default=0, null=True)),
                ('expenses', models.IntegerField(default=0, null=True)),
                ('recurring_expenses', models.IntegerField(default=0, null=True)),
                ('payment_made', models.IntegerField(default=0, null=True)),
                ('projects', models.IntegerField(default=0, null=True)),
                ('chart_of_accounts', models.IntegerField(default=0, null=True)),
                ('manual_journal', models.IntegerField(default=0, null=True)),
                ('eway_bill', models.IntegerField(default=0, null=True)),
                ('employees', models.IntegerField(default=0, null=True)),
                ('employees_loan', models.IntegerField(default=0, null=True)),
                ('holiday', models.IntegerField(default=0, null=True)),
                ('attendance', models.IntegerField(default=0, null=True)),
                ('salary_details', models.IntegerField(default=0, null=True)),
                ('reports', models.IntegerField(default=0, null=True)),
                ('update_action', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
    ]
